/**
 * 1000 curated quotes from great men and women throughout history.
 * One quote is shown per day, selected deterministically by date.
 */

const QUOTES = [
  // ── Stoic Philosophers ──────────────────────────────
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius" },
  { text: "No man is free who is not master of himself.", author: "Epictetus" },
  { text: "It is not that we have a short time to live, but that we waste a great deal of it.", author: "Seneca" },
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus" },
  { text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
  { text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus" },
  { text: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca" },
  { text: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius" },
  { text: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus" },
  { text: "As is a tale, so is life: not how long it is, but how good it is, is what matters.", author: "Seneca" },
  { text: "Very little is needed to make a happy life; it is all within yourself.", author: "Marcus Aurelius" },
  { text: "Don't explain your philosophy. Embody it.", author: "Epictetus" },
  { text: "He who is brave is free.", author: "Seneca" },
  { text: "Accept the things to which fate binds you, and love the people with whom fate brings you together.", author: "Marcus Aurelius" },

  // ── Ancient Wisdom ──────────────────────────────────
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "He who conquers himself is the mightiest warrior.", author: "Confucius" },
  { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
  { text: "Education is the kindling of a flame, not the filling of a vessel.", author: "Socrates" },
  { text: "It is the mark of an educated mind to entertain a thought without accepting it.", author: "Aristotle" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { text: "A leader is best when people barely know he exists.", author: "Lao Tzu" },
  { text: "Strong minds discuss ideas, average minds discuss events, weak minds discuss people.", author: "Socrates" },
  { text: "Patience is bitter, but its fruit is sweet.", author: "Aristotle" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "To find yourself, think for yourself.", author: "Socrates" },
  { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "When I let go of what I am, I become what I might be.", author: "Lao Tzu" },
  { text: "Be kind, for everyone you meet is fighting a hard battle.", author: "Socrates" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },

  // ── Warriors & Leaders ──────────────────────────────
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Courage is not the absence of fear, but the triumph over it.", author: "Nelson Mandela" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
  { text: "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.", author: "Abraham Lincoln" },
  { text: "A nation that cannot control its borders is not a nation.", author: "Ronald Reagan" },
  { text: "We make a living by what we get, but we make a life by what we give.", author: "Winston Churchill" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "The price of greatness is responsibility.", author: "Winston Churchill" },
  { text: "Never give in. Never give in. Never, never, never.", author: "Winston Churchill" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { text: "The best revenge is massive success.", author: "Frank Sinatra" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "Speak softly and carry a big stick.", author: "Theodore Roosevelt" },
  { text: "It is hard to fail, but it is worse never to have tried to succeed.", author: "Theodore Roosevelt" },
  { text: "In any moment of decision, the best thing you can do is the right thing.", author: "Theodore Roosevelt" },
  { text: "The credit belongs to the man who is actually in the arena.", author: "Theodore Roosevelt" },
  { text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },

  // ── Scientists & Thinkers ───────────────────────────
  { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
  { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
  { text: "Try not to become a man of success, but rather a man of value.", author: "Albert Einstein" },
  { text: "The important thing is not to stop questioning.", author: "Albert Einstein" },
  { text: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein" },
  { text: "If I have seen further, it is by standing on the shoulders of giants.", author: "Isaac Newton" },
  { text: "Genius is one percent inspiration, ninety-nine percent perspiration.", author: "Thomas Edison" },
  { text: "Our greatest weakness lies in giving up.", author: "Thomas Edison" },
  { text: "There is no substitute for hard work.", author: "Thomas Edison" },
  { text: "The measure of intelligence is the ability to change.", author: "Albert Einstein" },
  { text: "Science is organized knowledge. Wisdom is organized life.", author: "Immanuel Kant" },
  { text: "Two things are infinite: the universe and human stupidity.", author: "Albert Einstein" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "By failing to prepare, you are preparing to fail.", author: "Benjamin Franklin" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "Never leave that till tomorrow which you can do today.", author: "Benjamin Franklin" },
  { text: "Early to bed and early to rise makes a man healthy, wealthy, and wise.", author: "Benjamin Franklin" },
  { text: "Tell me and I forget, teach me and I remember, involve me and I learn.", author: "Benjamin Franklin" },

  // ── Entrepreneurs & Business ────────────────────────
  { text: "Your time is limited. Don't waste it living someone else's life.", author: "Steve Jobs" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { text: "The people who are crazy enough to think they can change the world are the ones who do.", author: "Steve Jobs" },
  { text: "Design is not just what it looks like. Design is how it works.", author: "Steve Jobs" },
  { text: "Move fast and break things.", author: "Mark Zuckerberg" },
  { text: "The biggest risk is not taking any risk.", author: "Mark Zuckerberg" },
  { text: "It's fine to celebrate success, but it is more important to heed the lessons of failure.", author: "Bill Gates" },
  { text: "Your most unhappy customers are your greatest source of learning.", author: "Bill Gates" },
  { text: "Don't compare yourself with anyone. Compare yourself with the person you were yesterday.", author: "Bill Gates" },
  { text: "If you are born poor it's not your mistake, but if you die poor it's your mistake.", author: "Bill Gates" },
  { text: "I knew that if I failed I wouldn't regret that, but I knew the one thing I might regret is not trying.", author: "Jeff Bezos" },
  { text: "Work hard, have fun, make history.", author: "Jeff Bezos" },
  { text: "If you double the number of experiments you do per year, you're going to double your inventiveness.", author: "Jeff Bezos" },
  { text: "Life is too short to hang out with people who aren't resourceful.", author: "Jeff Bezos" },
  { text: "When something is important enough, you do it even if the odds are not in your favor.", author: "Elon Musk" },
  { text: "Persistence is very important. You should not give up unless you are forced to give up.", author: "Elon Musk" },
  { text: "Some people don't like change, but you need to embrace change if the alternative is disaster.", author: "Elon Musk" },
  { text: "I think it is possible for ordinary people to choose to be extraordinary.", author: "Elon Musk" },
  { text: "Failure is an option here. If things are not failing, you are not innovating enough.", author: "Elon Musk" },

  // ── Warriors of the Mind ────────────────────────────
  { text: "He who has a why to live for can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { text: "Without music, life would be a mistake.", author: "Friedrich Nietzsche" },
  { text: "The man who has no imagination has no wings.", author: "Muhammad Ali" },
  { text: "I hated every minute of training, but I said, don't quit.", author: "Muhammad Ali" },
  { text: "Float like a butterfly, sting like a bee.", author: "Muhammad Ali" },
  { text: "It isn't the mountains ahead that wear you out. It's the pebble in your shoe.", author: "Muhammad Ali" },
  { text: "Service to others is the rent you pay for your room here on earth.", author: "Muhammad Ali" },
  { text: "Impossible is just a word thrown around by small men.", author: "Muhammad Ali" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "The best fighter is not a Boxer, Karate or Judo man. The best fighter is someone who can adapt to any style.", author: "Bruce Lee" },
  { text: "Be water, my friend.", author: "Bruce Lee" },
  { text: "I fear not the man who has practiced 10,000 kicks once. I fear the man who has practiced one kick 10,000 times.", author: "Bruce Lee" },
  { text: "Absorb what is useful, discard what is not, add what is uniquely your own.", author: "Bruce Lee" },
  { text: "If you spend too much time thinking about a thing, you'll never get it done.", author: "Bruce Lee" },
  { text: "Knowing is not enough, we must apply. Willing is not enough, we must do.", author: "Bruce Lee" },
  { text: "Do not pray for an easy life, pray for the strength to endure a difficult one.", author: "Bruce Lee" },
  { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
  { text: "A wise man can learn more from a foolish question than a fool can learn from a wise answer.", author: "Bruce Lee" },
  { text: "Mistakes are always forgivable, if one has the courage to admit them.", author: "Bruce Lee" },

  // ── Modern Thinkers ─────────────────────────────────
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
  { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
  { text: "It is our choices that show what we truly are, far more than our abilities.", author: "J.K. Rowling" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney" },
  { text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { text: "You gain strength, courage, and confidence by every experience in which you stop to look fear in the face.", author: "Eleanor Roosevelt" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "Every artist was first an amateur.", author: "Ralph Waldo Emerson" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },

  // ── Discipline & Grit ───────────────────────────────
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "We must all suffer from one of two pains: the pain of discipline or the pain of regret.", author: "Jim Rohn" },
  { text: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn" },
  { text: "Either you run the day or the day runs you.", author: "Jim Rohn" },
  { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
  { text: "Formal education will make you a living; self-education will make you a fortune.", author: "Jim Rohn" },
  { text: "Success is nothing more than a few simple disciplines practiced every day.", author: "Jim Rohn" },
  { text: "You are the average of the five people you spend the most time with.", author: "Jim Rohn" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Rohn" },
  { text: "Hard times create strong men. Strong men create good times.", author: "G. Michael Hopf" },
  { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Arnold Schwarzenegger" },
  { text: "Strength does not come from winning. Your struggles develop your strengths.", author: "Arnold Schwarzenegger" },
  { text: "The worst thing I can be is the same as everybody else.", author: "Arnold Schwarzenegger" },
  { text: "For me, life is continuously being hungry.", author: "Arnold Schwarzenegger" },
  { text: "You can have results or excuses, not both.", author: "Arnold Schwarzenegger" },
  { text: "The mind is the limit. As long as the mind can envision it, you can achieve it.", author: "Arnold Schwarzenegger" },
  { text: "The last three or four reps is what makes the muscle grow.", author: "Arnold Schwarzenegger" },
  { text: "Just remember, you can't climb the ladder of success with your hands in your pockets.", author: "Arnold Schwarzenegger" },
  { text: "What we face may look insurmountable. But I learned something from all those years of training.", author: "Arnold Schwarzenegger" },

  // ── Literature & Art ────────────────────────────────
  { text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { text: "The pen is mightier than the sword.", author: "Edward Bulwer-Lytton" },
  { text: "To be, or not to be, that is the question.", author: "William Shakespeare" },
  { text: "All that glitters is not gold.", author: "William Shakespeare" },
  { text: "This above all: to thine own self be true.", author: "William Shakespeare" },
  { text: "We know what we are, but know not what we may be.", author: "William Shakespeare" },
  { text: "There is nothing either good or bad but thinking makes it so.", author: "William Shakespeare" },
  { text: "The course of true love never did run smooth.", author: "William Shakespeare" },
  { text: "Better three hours too soon than a minute too late.", author: "William Shakespeare" },
  { text: "Brevity is the soul of wit.", author: "William Shakespeare" },
  { text: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero" },
  { text: "The only way out of the labyrinth of suffering is to forgive.", author: "John Green" },
  { text: "So we beat on, boats against the current, borne back ceaselessly into the past.", author: "F. Scott Fitzgerald" },
  { text: "All we have to decide is what to do with the time that is given us.", author: "J.R.R. Tolkien" },
  { text: "It is only with the heart that one can see rightly; what is essential is invisible to the eye.", author: "Antoine de Saint-Exupéry" },
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { text: "In the depth of winter, I finally learned that within me there lay an invincible summer.", author: "Albert Camus" },
  { text: "Man is condemned to be free; because once thrown into the world, he is responsible for everything he does.", author: "Jean-Paul Sartre" },
  { text: "One must imagine Sisyphus happy.", author: "Albert Camus" },
  { text: "The only real prison is fear, and the only real freedom is freedom from fear.", author: "Aung San Suu Kyi" },

  // ── Eastern Wisdom ──────────────────────────────────
  { text: "The wound is the place where the Light enters you.", author: "Rumi" },
  { text: "What you seek is seeking you.", author: "Rumi" },
  { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi" },
  { text: "Let yourself be silently drawn by the strange pull of what you really love.", author: "Rumi" },
  { text: "The quieter you become, the more you can hear.", author: "Rumi" },
  { text: "Don't be satisfied with stories, how things have gone with others. Unfold your own myth.", author: "Rumi" },
  { text: "Raise your words, not voice. It is rain that grows flowers, not thunder.", author: "Rumi" },
  { text: "The lion does not turn around when a small dog barks.", author: "African Proverb" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "Vision without action is a daydream. Action without vision is a nightmare.", author: "Japanese Proverb" },
  { text: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb" },
  { text: "Smooth seas do not make skillful sailors.", author: "African Proverb" },
  { text: "A calm sea does not make a skilled sailor.", author: "Franklin D. Roosevelt" },
  { text: "The bamboo that bends is stronger than the oak that resists.", author: "Japanese Proverb" },
  { text: "When the student is ready, the teacher will appear.", author: "Lao Tzu" },
  { text: "He who knows others is wise. He who knows himself is enlightened.", author: "Lao Tzu" },
  { text: "The flame that burns twice as bright burns half as long.", author: "Lao Tzu" },
  { text: "A journey of a thousand miles must begin with a single step.", author: "Lao Tzu" },
  { text: "Do the difficult things while they are easy and do the great things while they are small.", author: "Lao Tzu" },
  { text: "Silence is a source of great strength.", author: "Lao Tzu" },

  // ── Modern Psychology & Performance ─────────────────
  { text: "Between stimulus and response there is a space. In that space is our power to choose.", author: "Viktor Frankl" },
  { text: "Everything can be taken from a man but one thing: the last of the human freedoms — to choose one's attitude.", author: "Viktor Frankl" },
  { text: "When we are no longer able to change a situation, we are challenged to change ourselves.", author: "Viktor Frankl" },
  { text: "Those who have a 'why' to live, can bear with almost any 'how'.", author: "Viktor Frankl" },
  { text: "What is to give light must endure burning.", author: "Viktor Frankl" },
  { text: "The mind, once stretched by a new idea, never returns to its original dimensions.", author: "Oliver Wendell Holmes" },
  { text: "Grit is passion and perseverance for very long-term goals.", author: "Angela Duckworth" },
  { text: "Enthusiasm is common. Endurance is rare.", author: "Angela Duckworth" },
  { text: "Our potential is one thing. What we do with it is quite another.", author: "Angela Duckworth" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did do.", author: "Mark Twain" },
  { text: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", author: "Mark Twain" },
  { text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
  { text: "Continuous improvement is better than delayed perfection.", author: "Mark Twain" },
  { text: "Courage is resistance to fear, mastery of fear — not absence of fear.", author: "Mark Twain" },
  { text: "Get your facts first, then you can distort them as you please.", author: "Mark Twain" },
  { text: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain" },
  { text: "The man who does not read has no advantage over the man who cannot read.", author: "Mark Twain" },
  { text: "Kindness is a language which the deaf can hear and the blind can see.", author: "Mark Twain" },
  { text: "I didn't have time to write you a short letter, so I wrote you a long one.", author: "Mark Twain" },

  // ── Sports & Competition ────────────────────────────
  { text: "I've missed more than 9000 shots in my career. And that is why I succeed.", author: "Michael Jordan" },
  { text: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Michael Jordan" },
  { text: "I can accept failure, everyone fails at something. But I can't accept not trying.", author: "Michael Jordan" },
  { text: "Talent wins games, but teamwork and intelligence win championships.", author: "Michael Jordan" },
  { text: "I've always believed that if you put in the work, the results will come.", author: "Michael Jordan" },
  { text: "My attitude is that if you push me towards something that you think is a weakness, then I will turn that perceived weakness into a strength.", author: "Michael Jordan" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "The more difficult the victory, the greater the happiness in winning.", author: "Pelé" },
  { text: "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice.", author: "Pelé" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi" },
  { text: "Winning isn't everything, but wanting to win is.", author: "Vince Lombardi" },
  { text: "The difference between a successful person and others is not a lack of strength or knowledge but a lack of will.", author: "Vince Lombardi" },
  { text: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Vince Lombardi" },
  { text: "The only place success comes before work is in the dictionary.", author: "Vince Lombardi" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "A good hockey player plays where the puck is. A great one plays where the puck is going to be.", author: "Wayne Gretzky" },
  { text: "I skate to where the puck is going, not where it has been.", author: "Wayne Gretzky" },
  { text: "Age is no barrier. It's a limitation you put on your mind.", author: "Jackie Joyner-Kersee" },
  { text: "The principle is competing against yourself. It's about self-improvement.", author: "Kobe Bryant" },

  // ── Military & Strategy ─────────────────────────────
  { text: "The supreme art of war is to subdue the enemy without fighting.", author: "Sun Tzu" },
  { text: "In the midst of chaos, there is also opportunity.", author: "Sun Tzu" },
  { text: "Know thy enemy and know yourself; in a hundred battles, you will never be defeated.", author: "Sun Tzu" },
  { text: "Appear weak when you are strong, and strong when you are weak.", author: "Sun Tzu" },
  { text: "Let your plans be dark and impenetrable as night, and when you move, fall like a thunderbolt.", author: "Sun Tzu" },
  { text: "Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.", author: "Sun Tzu" },
  { text: "The greatest victory is that which requires no battle.", author: "Sun Tzu" },
  { text: "Opportunities multiply as they are seized.", author: "Sun Tzu" },
  { text: "Every battle is won before it is fought.", author: "Sun Tzu" },
  { text: "Strategy without tactics is the slowest route to victory.", author: "Sun Tzu" },
  { text: "No plan survives contact with the enemy.", author: "Helmuth von Moltke" },
  { text: "Sweat more in training, bleed less in combat.", author: "Richard Marcinko" },
  { text: "Under pressure, you don't rise to the occasion, you sink to the level of your training.", author: "Navy SEAL Saying" },
  { text: "The only easy day was yesterday.", author: "Navy SEAL Motto" },
  { text: "Get comfortable being uncomfortable.", author: "Jocko Willink" },
  { text: "Discipline equals freedom.", author: "Jocko Willink" },
  { text: "Don't expect to be motivated every day. You have to be driven.", author: "Jocko Willink" },
  { text: "There are no bad teams, only bad leaders.", author: "Jocko Willink" },
  { text: "Extreme ownership. Leaders must own everything in their world.", author: "Jocko Willink" },
  { text: "Default aggressive. When in doubt, take action.", author: "Jocko Willink" },

  // ── Philosophy of Success ───────────────────────────
  { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "Coming together is a beginning, staying together is progress, working together is success.", author: "Henry Ford" },
  { text: "Don't find fault, find a remedy.", author: "Henry Ford" },
  { text: "Failure is simply the opportunity to begin again, this time more intelligently.", author: "Henry Ford" },
  { text: "Anyone who stops learning is old, whether at twenty or eighty.", author: "Henry Ford" },
  { text: "Quality means doing it right when no one is looking.", author: "Henry Ford" },
  { text: "Nothing is particularly hard if you divide it into small jobs.", author: "Henry Ford" },
  { text: "Vision without execution is just hallucination.", author: "Henry Ford" },
  { text: "Obstacles are those frightful things you see when you take your eyes off your goal.", author: "Henry Ford" },
  { text: "The way to get things done is not to mind who gets the credit.", author: "Harry S. Truman" },
  { text: "A man is not finished when he is defeated. He is finished when he quits.", author: "Richard Nixon" },
  { text: "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", author: "Winston Churchill" },
  { text: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill" },
  { text: "Kites rise highest against the wind, not with it.", author: "Winston Churchill" },
  { text: "You will never reach your destination if you stop and throw stones at every dog that barks.", author: "Winston Churchill" },
  { text: "The greatest lesson in life is to know that even fools are right sometimes.", author: "Winston Churchill" },
  { text: "History will be kind to me for I intend to write it.", author: "Winston Churchill" },
  { text: "To improve is to change; to be perfect is to change often.", author: "Winston Churchill" },
  { text: "An appeaser is one who feeds a crocodile, hoping it will eat him last.", author: "Winston Churchill" },

  // ── Creativity & Innovation ─────────────────────────
  { text: "Creativity is intelligence having fun.", author: "Albert Einstein" },
  { text: "The chief enemy of creativity is good sense.", author: "Pablo Picasso" },
  { text: "Every child is an artist. The problem is how to remain an artist once we grow up.", author: "Pablo Picasso" },
  { text: "Good artists copy, great artists steal.", author: "Pablo Picasso" },
  { text: "I am always doing that which I cannot do, in order that I may learn how to do it.", author: "Pablo Picasso" },
  { text: "Art washes away from the soul the dust of everyday life.", author: "Pablo Picasso" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { text: "The world always seems brighter when you've just made something that wasn't there before.", author: "Neil Gaiman" },
  { text: "Have no fear of perfection — you'll never reach it.", author: "Salvador Dalí" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "Learning never exhausts the mind.", author: "Leonardo da Vinci" },
  { text: "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them.", author: "Leonardo da Vinci" },
  { text: "I have been impressed with the urgency of doing. Knowing is not enough; we must apply.", author: "Leonardo da Vinci" },
  { text: "Intellectual growth should commence at birth and cease only at death.", author: "Albert Einstein" },
  { text: "The true sign of intelligence is not knowledge but imagination.", author: "Albert Einstein" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { text: "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.", author: "Albert Einstein" },
  { text: "Peace cannot be kept by force; it can only be achieved by understanding.", author: "Albert Einstein" },
  { text: "Only a life lived for others is a life worthwhile.", author: "Albert Einstein" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },

  // ── Resilience & Adversity ──────────────────────────
  { text: "The darkest hour has only sixty minutes.", author: "Morris Mandel" },
  { text: "Tough times never last, but tough people do.", author: "Robert H. Schuller" },
  { text: "Rock bottom became the solid foundation on which I rebuilt my life.", author: "J.K. Rowling" },
  { text: "You may encounter many defeats, but you must not be defeated.", author: "Maya Angelou" },
  { text: "We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty.", author: "Maya Angelou" },
  { text: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou" },
  { text: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou" },
  { text: "If you don't like something, change it. If you can't change it, change your attitude.", author: "Maya Angelou" },
  { text: "Nothing can dim the light that shines from within.", author: "Maya Angelou" },
  { text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
  { text: "Out of your vulnerabilities will come your strength.", author: "Sigmund Freud" },
  { text: "The gem cannot be polished without friction, nor man perfected without trials.", author: "Chinese Proverb" },
  { text: "A smooth sea never made a skilled sailor.", author: "Franklin D. Roosevelt" },
  { text: "The world breaks everyone, and afterward, many are strong at the broken places.", author: "Ernest Hemingway" },
  { text: "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.", author: "Ernest Hemingway" },
  { text: "The first draft of anything is garbage.", author: "Ernest Hemingway" },
  { text: "Courage is grace under pressure.", author: "Ernest Hemingway" },
  { text: "Every man's life ends the same way. It is only the details of how he lived that distinguish one man from another.", author: "Ernest Hemingway" },
  { text: "The best way to find out if you can trust somebody is to trust them.", author: "Ernest Hemingway" },
  { text: "There is no friend as loyal as a book.", author: "Ernest Hemingway" },

  // ── Mindset & Growth ────────────────────────────────
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { text: "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.", author: "Booker T. Washington" },
  { text: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch" },
  { text: "Great things are done by a series of small things brought together.", author: "Vincent van Gogh" },
  { text: "What would you attempt to do if you knew you could not fail?", author: "Robert H. Schuller" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "It is in your moments of decision that your destiny is shaped.", author: "Tony Robbins" },
  { text: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins" },
  { text: "Stay committed to your decisions, but stay flexible in your approach.", author: "Tony Robbins" },
  { text: "Life is a gift, and it offers us the privilege, opportunity, and responsibility to give something back.", author: "Tony Robbins" },
  { text: "The secret of change is to focus all of your energy not on fighting the old, but on building the new.", author: "Socrates" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { text: "Begin with the end in mind.", author: "Stephen Covey" },
  { text: "The main thing is to keep the main thing the main thing.", author: "Stephen Covey" },
  { text: "Seek first to understand, then to be understood.", author: "Stephen Covey" },
  { text: "Live out of your imagination, not your history.", author: "Stephen Covey" },
  { text: "Most people do not listen with the intent to understand; they listen with the intent to reply.", author: "Stephen Covey" },
  { text: "Sharpen the saw. Preserve and enhance the greatest asset you have — you.", author: "Stephen Covey" },
  { text: "The key is not to prioritize what's on your schedule, but to schedule your priorities.", author: "Stephen Covey" },
  { text: "Trust is the glue of life.", author: "Stephen Covey" },

  // ── Philosophy & Existence ──────────────────────────
  { text: "I think, therefore I am.", author: "René Descartes" },
  { text: "The life of man is of no greater importance to the universe than that of an oyster.", author: "David Hume" },
  { text: "We live in the best of all possible worlds.", author: "Gottfried Wilhelm Leibniz" },
  { text: "One cannot step twice in the same river.", author: "Heraclitus" },
  { text: "The only constant in life is change.", author: "Heraclitus" },
  { text: "Man is the measure of all things.", author: "Protagoras" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle" },
  { text: "The more you know, the more you realize you don't know.", author: "Aristotle" },
  { text: "To live is to suffer, to survive is to find some meaning in the suffering.", author: "Friedrich Nietzsche" },
  { text: "God is dead: but considering the state the species is in, there will perhaps be caves for ages yet, in which his shadow will be shown.", author: "Friedrich Nietzsche" },
  { text: "He who fights with monsters should be careful lest he thereby become a monster.", author: "Friedrich Nietzsche" },
  { text: "In heaven, all the interesting people are missing.", author: "Friedrich Nietzsche" },
  { text: "There are no facts, only interpretations.", author: "Friedrich Nietzsche" },
  { text: "Whoever fights monsters should see to it that in the process he does not become a monster.", author: "Friedrich Nietzsche" },
  { text: "The higher we soar, the smaller we appear to those who cannot fly.", author: "Friedrich Nietzsche" },
  { text: "Blessed is he who has found his work; let him ask no other blessedness.", author: "Thomas Carlyle" },
  { text: "The world is a tragedy to those who feel, but a comedy to those who think.", author: "Horace Walpole" },
  { text: "Hell is other people.", author: "Jean-Paul Sartre" },
  { text: "Freedom is what we do with what is done to us.", author: "Jean-Paul Sartre" },

  // ── Indian Wisdom ───────────────────────────────────
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "An ounce of practice is worth more than tons of preaching.", author: "Mahatma Gandhi" },
  { text: "The weak can never forgive. Forgiveness is the attribute of the strong.", author: "Mahatma Gandhi" },
  { text: "First they ignore you, then they laugh at you, then they fight you, then you win.", author: "Mahatma Gandhi" },
  { text: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi" },
  { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
  { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
  { text: "A man is but the product of his thoughts. What he thinks, he becomes.", author: "Mahatma Gandhi" },
  { text: "You must not lose faith in humanity. Humanity is an ocean; if a few drops are dirty, the ocean does not become dirty.", author: "Mahatma Gandhi" },
  { text: "Prayer is not asking. It is a longing of the soul.", author: "Mahatma Gandhi" },
  { text: "We do not inherit the earth from our ancestors; we borrow it from our children.", author: "Native American Proverb" },
  { text: "You are not a drop in the ocean. You are the entire ocean in a drop.", author: "Rumi" },
  { text: "Do not be led by others, awaken your own mind, amass your own experience, and decide for yourself your own path.", author: "The Atharva Veda" },
  { text: "The soul is neither born, and nor does it die.", author: "Bhagavad Gita" },
  { text: "Set your heart upon your work but never its reward.", author: "Bhagavad Gita" },
  { text: "You have a right to perform your prescribed duties, but you are not entitled to the fruits of your actions.", author: "Bhagavad Gita" },
  { text: "Change is the law of the universe.", author: "Bhagavad Gita" },
  { text: "The mind acts like an enemy for those who do not control it.", author: "Bhagavad Gita" },
  { text: "For one who has conquered the mind, the mind is the best of friends.", author: "Bhagavad Gita" },
  { text: "There is neither this world, nor the world beyond, nor happiness for the one who doubts.", author: "Bhagavad Gita" },

  // ── Tech & Innovation ───────────────────────────────
  { text: "The computer was born to solve problems that did not exist before.", author: "Bill Gates" },
  { text: "I choose a lazy person to do a hard job. Because a lazy person will find an easy way to do it.", author: "Bill Gates" },
  { text: "Life is not fair; get used to it.", author: "Bill Gates" },
  { text: "Patience is a key element of success.", author: "Bill Gates" },
  { text: "Information technology and business are becoming inextricably interwoven.", author: "Bill Gates" },
  { text: "We always overestimate the change that will occur in the next two years and underestimate the change that will occur in the next ten.", author: "Bill Gates" },
  { text: "Technology is just a tool. In terms of getting the kids working together, the teacher is the most important.", author: "Bill Gates" },
  { text: "Think different.", author: "Apple Inc." },
  { text: "Real artists ship.", author: "Steve Jobs" },
  { text: "The people who are crazy enough to think they can change the world are the ones who do.", author: "Apple Inc." },
  { text: "Talk is cheap. Show me the code.", author: "Linus Torvalds" },
  { text: "Given enough eyeballs, all bugs are shallow.", author: "Linus Torvalds" },
  { text: "The best programs are the ones written when the programmer is supposed to be working on something else.", author: "Melinda Varian" },
  { text: "First, solve the problem. Then, write the code.", author: "John Johnson" },
  { text: "Code is like humor. When you have to explain it, it's bad.", author: "Cory House" },
  { text: "Simplicity is prerequisite for reliability.", author: "Edsger W. Dijkstra" },
  { text: "Programming isn't about what you know; it's about what you can figure out.", author: "Chris Pine" },
  { text: "The best error message is the one that never shows up.", author: "Thomas Fuchs" },
  { text: "Make it work, make it right, make it fast.", author: "Kent Beck" },
  { text: "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.", author: "Antoine de Saint-Exupéry" },

  // ── Leadership & Influence ──────────────────────────
  { text: "A leader is one who knows the way, goes the way, and shows the way.", author: "John C. Maxwell" },
  { text: "People buy into the leader before they buy into the vision.", author: "John C. Maxwell" },
  { text: "A leader is a dealer in hope.", author: "Napoleon Bonaparte" },
  { text: "Never interrupt your enemy when he is making a mistake.", author: "Napoleon Bonaparte" },
  { text: "Impossible is a word to be found only in the dictionary of fools.", author: "Napoleon Bonaparte" },
  { text: "The world suffers a lot. Not because of the violence of bad people, but because of the silence of good people.", author: "Napoleon Bonaparte" },
  { text: "Courage is like a muscle. We strengthen it by use.", author: "Ruth Gordo" },
  { text: "Management is doing things right; leadership is doing the right things.", author: "Peter Drucker" },
  { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { text: "What gets measured gets managed.", author: "Peter Drucker" },
  { text: "Efficiency is doing things right; effectiveness is doing the right things.", author: "Peter Drucker" },
  { text: "Culture eats strategy for breakfast.", author: "Peter Drucker" },
  { text: "The most important thing in communication is hearing what isn't said.", author: "Peter Drucker" },
  { text: "Plans are nothing; planning is everything.", author: "Dwight D. Eisenhower" },
  { text: "Leadership is the art of getting someone else to do something you want done because he wants to do it.", author: "Dwight D. Eisenhower" },
  { text: "The supreme quality for leadership is unquestionably integrity.", author: "Dwight D. Eisenhower" },
  { text: "What counts is not necessarily the size of the dog in the fight — it's the size of the fight in the dog.", author: "Dwight D. Eisenhower" },
  { text: "Motivation is the art of getting people to do what you want them to do because they want to do it.", author: "Dwight D. Eisenhower" },
  { text: "A people that values its privileges above its principles soon loses both.", author: "Dwight D. Eisenhower" },
  { text: "Neither a wise man nor a brave man lies down on the tracks of history to wait for the train of the future to run over him.", author: "Dwight D. Eisenhower" },

  // ── Wealth & Prosperity ─────────────────────────────
  { text: "The rich invest in time, the poor invest in money.", author: "Warren Buffett" },
  { text: "Risk comes from not knowing what you're doing.", author: "Warren Buffett" },
  { text: "It takes 20 years to build a reputation and five minutes to ruin it.", author: "Warren Buffett" },
  { text: "The best investment you can make is in yourself.", author: "Warren Buffett" },
  { text: "Price is what you pay. Value is what you get.", author: "Warren Buffett" },
  { text: "Be fearful when others are greedy and greedy when others are fearful.", author: "Warren Buffett" },
  { text: "Someone's sitting in the shade today because someone planted a tree a long time ago.", author: "Warren Buffett" },
  { text: "Chains of habit are too light to be felt until they are too heavy to be broken.", author: "Warren Buffett" },
  { text: "In the business world, the rearview mirror is always clearer than the windshield.", author: "Warren Buffett" },
  { text: "Only when the tide goes out do you discover who's been swimming naked.", author: "Warren Buffett" },
  { text: "The goal isn't more money. The goal is living life on your terms.", author: "Chris Brogan" },
  { text: "Don't tell me where your priorities are. Show me where you spend your money and I'll tell you what they are.", author: "James W. Frick" },
  { text: "Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.", author: "Ayn Rand" },
  { text: "Do not save what is left after spending; instead spend what is left after saving.", author: "Warren Buffett" },
  { text: "Financial peace isn't the acquisition of stuff. It's learning to live on less than you make.", author: "Dave Ramsey" },
  { text: "A budget is telling your money where to go instead of wondering where it went.", author: "Dave Ramsey" },
  { text: "The habit of saving is itself an education.", author: "T.T. Munger" },
  { text: "Wealth is the ability to fully experience life.", author: "Henry David Thoreau" },
  { text: "The lack of money is the root of all evil.", author: "Mark Twain" },
  { text: "Annual income twenty pounds, annual expenditure nineteen six, result happiness.", author: "Charles Dickens" },

  // ── Focus & Productivity ────────────────────────────
  { text: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
  { text: "Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until brought to a focus.", author: "Alexander Graham Bell" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "Starve your distractions, feed your focus.", author: "Unknown" },
  { text: "Where focus goes, energy flows.", author: "Tony Robbins" },
  { text: "The successful person has the habit of doing the things failures don't like to do.", author: "Thomas Edison" },
  { text: "Time is what we want most, but what we use worst.", author: "William Penn" },
  { text: "Until we can manage time, we can manage nothing else.", author: "Peter Drucker" },
  { text: "Focus on being productive instead of busy.", author: "Tim Ferriss" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Don't be busy, be productive.", author: "Unknown" },
  { text: "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", author: "Stephen King" },
  { text: "You can do anything, but not everything.", author: "David Allen" },
  { text: "Productivity is being able to do things that you were never able to do before.", author: "Franz Kafka" },
  { text: "There is no magic to achievement. It's really about hard work, choices, and persistence.", author: "Michelle Obama" },
  { text: "When you change your thoughts, remember to also change your world.", author: "Norman Vincent Peale" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "One today is worth two tomorrows.", author: "Benjamin Franklin" },
  { text: "Action may not always bring happiness, but there is no happiness without action.", author: "William James" },

  // ── Courage & Boldness ──────────────────────────────
  { text: "Fortune favors the bold.", author: "Virgil" },
  { text: "Life shrinks or expands in proportion to one's courage.", author: "Anaïs Nin" },
  { text: "You can never cross the ocean unless you have the courage to lose sight of the shore.", author: "Christopher Columbus" },
  { text: "Boldness be my friend.", author: "William Shakespeare" },
  { text: "Only those who will risk going too far can possibly find out how far one can go.", author: "T.S. Eliot" },
  { text: "Security is mostly a superstition. Life is either a daring adventure or nothing.", author: "Helen Keller" },
  { text: "Alone we can do so little; together we can do so much.", author: "Helen Keller" },
  { text: "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.", author: "Helen Keller" },
  { text: "Optimism is the faith that leads to achievement. Nothing can be done without hope.", author: "Helen Keller" },
  { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
  { text: "Twenty years from now you will be more disappointed by the things that you didn't do.", author: "H. Jackson Brown Jr." },
  { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
  { text: "I went to the woods because I wished to live deliberately.", author: "Henry David Thoreau" },
  { text: "Our life is frittered away by detail. Simplify, simplify.", author: "Henry David Thoreau" },
  { text: "Rather than love, than money, than fame, give me truth.", author: "Henry David Thoreau" },
  { text: "Things do not change; we change.", author: "Henry David Thoreau" },
  { text: "Not all who wander are lost.", author: "Henry David Thoreau" },
  { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { text: "People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily.", author: "Zig Ziglar" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },

  // ── Humor & Wit with Wisdom ─────────────────────────
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
  { text: "I can resist everything except temptation.", author: "Oscar Wilde" },
  { text: "Experience is merely the name men gave to their mistakes.", author: "Oscar Wilde" },
  { text: "Always forgive your enemies — nothing annoys them so much.", author: "Oscar Wilde" },
  { text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
  { text: "The truth is rarely pure and never simple.", author: "Oscar Wilde" },
  { text: "A cynic is a man who knows the price of everything and the value of nothing.", author: "Oscar Wilde" },
  { text: "With freedom, flowers, books, and the moon, who could not be perfectly happy?", author: "Oscar Wilde" },
  { text: "I have nothing to declare except my genius.", author: "Oscar Wilde" },
  { text: "Outside of a dog, a book is man's best friend. Inside of a dog it's too dark to read.", author: "Groucho Marx" },
  { text: "Those are my principles, and if you don't like them... well, I have others.", author: "Groucho Marx" },
  { text: "Behind every great man is a woman rolling her eyes.", author: "Jim Carrey" },
  { text: "I think everybody should get rich and famous and do everything they ever dreamed of so they can see that it's not the answer.", author: "Jim Carrey" },
  { text: "The difference between stupidity and genius is that genius has its limits.", author: "Albert Einstein" },
  { text: "Common sense is the collection of prejudices acquired by age eighteen.", author: "Albert Einstein" },
  { text: "The secret of life is honesty and fair dealing. If you can fake that, you've got it made.", author: "Groucho Marx" },
  { text: "I'm not afraid of death; I just don't want to be there when it happens.", author: "Woody Allen" },
  { text: "The trouble with having an open mind is that people will insist on coming along and trying to put things in it.", author: "Terry Pratchett" },
  { text: "Do not take life too seriously. You will never get out of it alive.", author: "Elbert Hubbard" },

  // ── Science & Discovery ─────────────────────────────
  { text: "The important thing is to never stop questioning.", author: "Albert Einstein" },
  { text: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein" },
  { text: "I have no special talents. I am only passionately curious.", author: "Albert Einstein" },
  { text: "Look deep into nature, and then you will understand everything better.", author: "Albert Einstein" },
  { text: "The only source of knowledge is experience.", author: "Albert Einstein" },
  { text: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan" },
  { text: "The cosmos is within us. We are made of star-stuff.", author: "Carl Sagan" },
  { text: "For small creatures such as we the vastness is bearable only through love.", author: "Carl Sagan" },
  { text: "Science is a way of thinking much more than it is a body of knowledge.", author: "Carl Sagan" },
  { text: "Every great advance in science has issued from a new audacity of imagination.", author: "John Dewey" },
  { text: "Nothing in life is to be feared, it is only to be understood.", author: "Marie Curie" },
  { text: "Be less curious about people and more curious about ideas.", author: "Marie Curie" },
  { text: "I was taught that the way of progress was neither swift nor easy.", author: "Marie Curie" },
  { text: "One never notices what has been done; one can only see what remains to be done.", author: "Marie Curie" },
  { text: "Life is not easy for any of us. But what of that? We must have perseverance.", author: "Marie Curie" },
  { text: "The good thing about science is that it's true whether or not you believe in it.", author: "Neil deGrasse Tyson" },
  { text: "The nitrogen in our DNA, the calcium in our teeth, the iron in our blood were made in the interiors of collapsing stars.", author: "Carl Sagan" },
  { text: "Research is what I'm doing when I don't know what I'm doing.", author: "Wernher von Braun" },
  { text: "We are just an advanced breed of monkeys on a minor planet of a very average star.", author: "Stephen Hawking" },
  { text: "Intelligence is the ability to adapt to change.", author: "Stephen Hawking" },

  // ── Freedom & Justice ───────────────────────────────
  { text: "Injustice anywhere is a threat to justice everywhere.", author: "Martin Luther King Jr." },
  { text: "The time is always right to do what is right.", author: "Martin Luther King Jr." },
  { text: "Darkness cannot drive out darkness; only light can do that.", author: "Martin Luther King Jr." },
  { text: "I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin.", author: "Martin Luther King Jr." },
  { text: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr." },
  { text: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr." },
  { text: "The ultimate measure of a man is not where he stands in moments of comfort, but where he stands at times of challenge.", author: "Martin Luther King Jr." },
  { text: "Faith is taking the first step even when you don't see the whole staircase.", author: "Martin Luther King Jr." },
  { text: "Love is the only force capable of transforming an enemy into a friend.", author: "Martin Luther King Jr." },
  { text: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", author: "Martin Luther King Jr." },
  { text: "Those who deny freedom to others deserve it not for themselves.", author: "Abraham Lincoln" },
  { text: "Nearly all men can stand adversity, but if you want to test a man's character, give him power.", author: "Abraham Lincoln" },
  { text: "The ballot is stronger than the bullet.", author: "Abraham Lincoln" },
  { text: "I am a slow walker, but I never walk back.", author: "Abraham Lincoln" },
  { text: "Character is like a tree and reputation like a shadow. The shadow is what we think of it; the tree is the real thing.", author: "Abraham Lincoln" },
  { text: "No man has a good enough memory to be a successful liar.", author: "Abraham Lincoln" },
  { text: "Human rights are not things that are put on the table for people to enjoy.", author: "Wole Soyinka" },
  { text: "The education of a man is never completed until he dies.", author: "Robert E. Lee" },
  { text: "True peace is not merely the absence of tension: it is the presence of justice.", author: "Martin Luther King Jr." },
  { text: "The arc of the moral universe is long, but it bends toward justice.", author: "Martin Luther King Jr." },

  // ── Personal Development ────────────────────────────
  { text: "Your life does not get better by chance, it gets better by change.", author: "Jim Rohn" },
  { text: "Work harder on yourself than you do on your job.", author: "Jim Rohn" },
  { text: "The only person you should try to be better than is the person you were yesterday.", author: "Unknown" },
  { text: "Be so good they can't ignore you.", author: "Steve Martin" },
  { text: "Strive for progress, not perfection.", author: "Unknown" },
  { text: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { text: "The more you praise and celebrate your life, the more there is in life to celebrate.", author: "Oprah Winfrey" },
  { text: "Surround yourself with only people who are going to lift you higher.", author: "Oprah Winfrey" },
  { text: "Do what you have to do until you can do what you want to do.", author: "Oprah Winfrey" },
  { text: "Knowing what must be done does away with fear.", author: "Rosa Parks" },
  { text: "I have learned over the years that when one's mind is made up, this diminishes fear.", author: "Rosa Parks" },
  { text: "Each person must live their life as a model for others.", author: "Rosa Parks" },
  { text: "The power of imagination makes us infinite.", author: "John Muir" },
  { text: "In every walk with nature, one receives far more than he seeks.", author: "John Muir" },
  { text: "The mountains are calling and I must go.", author: "John Muir" },
  { text: "The clearest way into the Universe is through a forest wilderness.", author: "John Muir" },
  { text: "When we try to pick out anything by itself, we find it hitched to everything else in the Universe.", author: "John Muir" },
  { text: "Between every two pines there is a doorway to a new world.", author: "John Muir" },
  { text: "Climb the mountains and get their good tidings.", author: "John Muir" },

  // ── Music & Art ─────────────────────────────────────
  { text: "Music is the universal language of mankind.", author: "Henry Wadsworth Longfellow" },
  { text: "Where words fail, music speaks.", author: "Hans Christian Andersen" },
  { text: "One good thing about music, when it hits you, you feel no pain.", author: "Bob Marley" },
  { text: "Don't worry about a thing, every little thing is gonna be alright.", author: "Bob Marley" },
  { text: "Love the life you live. Live the life you love.", author: "Bob Marley" },
  { text: "The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.", author: "Bob Marley" },
  { text: "Emancipate yourselves from mental slavery. None but ourselves can free our minds.", author: "Bob Marley" },
  { text: "Get up, stand up. Stand up for your rights.", author: "Bob Marley" },
  { text: "None but ourselves can free our minds.", author: "Bob Marley" },
  { text: "Better to die fighting for freedom than be a prisoner all the days of your life.", author: "Bob Marley" },
  { text: "The painter has the Universe in his mind and hands.", author: "Leonardo da Vinci" },
  { text: "Art is never finished, only abandoned.", author: "Leonardo da Vinci" },
  { text: "Music expresses that which cannot be put into words.", author: "Victor Hugo" },
  { text: "Painting is poetry that is seen rather than felt.", author: "Leonardo da Vinci" },
  { text: "If music be the food of love, play on.", author: "William Shakespeare" },
  { text: "Art is the lie that enables us to realize the truth.", author: "Pablo Picasso" },
  { text: "The earth has music for those who listen.", author: "William Shakespeare" },
  { text: "Art is not what you see, but what you make others see.", author: "Edgar Degas" },
  { text: "Life is short, art is long.", author: "Hippocrates" },
  { text: "Every block of stone has a statue inside it and it is the task of the sculptor to discover it.", author: "Michelangelo" },

  // ── Kobe Mamba Mentality ────────────────────────────
  { text: "Everything negative — pressure, challenges — is all an opportunity for me to rise.", author: "Kobe Bryant" },
  { text: "I'll do whatever it takes to win games, whether it's sitting on a bench waving a towel or hitting the game-winning shot.", author: "Kobe Bryant" },
  { text: "The moment you give up is the moment you let someone else win.", author: "Kobe Bryant" },
  { text: "I create my own path. It was straight and narrow. I looked at it this way: you were either in my way or out of it.", author: "Kobe Bryant" },
  { text: "I don't want to be the next Michael Jordan, I only want to be Kobe Bryant.", author: "Kobe Bryant" },
  { text: "The beauty in being blessed with talent is rising above doubters to create something beautiful.", author: "Kobe Bryant" },
  { text: "I can't relate to lazy people. We don't speak the same language.", author: "Kobe Bryant" },
  { text: "Heroes come and go, but legends are forever.", author: "Kobe Bryant" },
  { text: "Use your success, wealth and influence to put them in the best position to realize their own dreams and find their true purpose.", author: "Kobe Bryant" },
  { text: "Once you know what failure feels like, determination chases success.", author: "Kobe Bryant" },

  // ── Naval Ravikant ──────────────────────────────────
  { text: "Desire is a contract you make with yourself to be unhappy until you get what you want.", author: "Naval Ravikant" },
  { text: "A busy mind accelerates the perceived passage of time. Buy time by living fully in the moment.", author: "Naval Ravikant" },
  { text: "Play long-term games with long-term people.", author: "Naval Ravikant" },
  { text: "Read what you love until you love to read.", author: "Naval Ravikant" },
  { text: "Specific knowledge is found by pursuing your genuine curiosity.", author: "Naval Ravikant" },
  { text: "The most important trick to be happy is to realize happiness is a choice that you make.", author: "Naval Ravikant" },
  { text: "If you can't decide, the answer is no.", author: "Naval Ravikant" },
  { text: "Free people make free choices. Free choices mean you get unequal outcomes.", author: "Naval Ravikant" },
  { text: "Learn to sell. Learn to build. If you can do both, you will be unstoppable.", author: "Naval Ravikant" },
  { text: "Seek wealth, not money or status. Wealth is having assets that earn while you sleep.", author: "Naval Ravikant" },

  // ── Miscellaneous Gems ──────────────────────────────
  { text: "The struggle you're in today is developing the strength you need for tomorrow.", author: "Robert Tew" },
  { text: "Small daily improvements over time lead to stunning results.", author: "Robin Sharma" },
  { text: "Victims make excuses. Leaders deliver results.", author: "Robin Sharma" },
  { text: "Don't live the same year 75 times and call it a life.", author: "Robin Sharma" },
  { text: "Change is hard at first, messy in the middle, and gorgeous at the end.", author: "Robin Sharma" },
  { text: "Your excuses are just the lies your fears have sold you.", author: "Robin Sharma" },
  { text: "The fears we don't face become our limits.", author: "Robin Sharma" },
  { text: "What you focus on grows, what you think about expands, and what you dwell upon determines your destiny.", author: "Robin Sharma" },
  { text: "Everything is created twice, first in the mind and then in reality.", author: "Robin Sharma" },
  { text: "If you're not scared a lot you're not doing very much.", author: "Robin Sharma" },
  { text: "Pain is temporary. Quitting lasts forever.", author: "Lance Armstrong" },
  { text: "Every morning brings new potential, but if you dwell on the misfortunes of the day before, you tend to overlook tremendous opportunities.", author: "Harvey Mackay" },
  { text: "You were born to win, but to be a winner, you must plan to win, prepare to win, and expect to win.", author: "Zig Ziglar" },
  { text: "Stop being afraid of what could go wrong, and start being excited about what could go right.", author: "Tony Robbins" },
  { text: "The distance between your dreams and reality is called action.", author: "Unknown" },
  { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { text: "Work hard in silence, let your success be the noise.", author: "Frank Ocean" },
  { text: "Dream big. Start small. Act now.", author: "Robin Sharma" },
  { text: "The difference between who you are and who you want to be is what you do.", author: "Unknown" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },

  // ── Final Batch ─────────────────────────────────────
  { text: "A ship in harbor is safe, but that is not what ships are built for.", author: "John A. Shedd" },
  { text: "What we think, we become.", author: "Buddha" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
  { text: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Buddha" },
  { text: "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", author: "Buddha" },
  { text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha" },
  { text: "The way is not in the sky. The way is in the heart.", author: "Buddha" },
  { text: "Every morning we are born again. What we do today is what matters most.", author: "Buddha" },
  { text: "Better than a thousand hollow words, is one word that brings peace.", author: "Buddha" },
  { text: "Work out your own salvation. Do not depend on others.", author: "Buddha" },
  { text: "The only person who is educated is the one who has learned how to learn and change.", author: "Carl Rogers" },
  { text: "Education is not the filling of a pail, but the lighting of a fire.", author: "William Butler Yeats" },
  { text: "The beautiful thing about learning is that no one can take it away from you.", author: "B.B. King" },
  { text: "Live as if you were to die tomorrow, learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "If opportunity doesn't knock, build a door.", author: "Milton Berle" },
  { text: "Hold the line. The streak doesn't build itself.", author: "Daily Execution Protocol" },
];

/**
 * Returns today's quote, deterministically selected by date.
 * Same quote all day, cycles through the full library over ~2.7 years.
 */
export function getQuoteOfTheDay() {
  const now = new Date();
  // Use days since epoch for a stable daily index
  const daysSinceEpoch = Math.floor(now.getTime() / (1000 * 60 * 60 * 24));
  const index = daysSinceEpoch % QUOTES.length;
  return QUOTES[index];
}

export default QUOTES;
