// SEBI Grade A IT Exam Question Bank for DBMS & SQL

export const SEBI_EXAM_QUESTIONS = [
  {
    id: "q1",
    topic: "ER Modeling",
    question: "In an ER model, if every instance of entity type E1 must participate in at least one relationship instance of R with E2, the participation of E1 in R is said to be:",
    options: [
      "A) Partial Participation",
      "B) Total Participation (Existence Dependency)",
      "C) Disjoint Participation",
      "D) Overlapping Participation"
    ],
    correctAnswer: 1,
    explanation: "Total participation (indicated by double lines in ER diagrams) specifies that every entity instance in the entity set must participate in at least one relationship instance."
  },
  {
    id: "q2",
    topic: "Keys & Integrity",
    question: "Given a relation R(A, B, C, D) with functional dependencies {A -> B, B -> C, C -> D}. What is the primary candidate key of R?",
    options: [
      "A) {B}",
      "B) {C}",
      "C) {A}",
      "D) {A, B}"
    ],
    correctAnswer: 2,
    explanation: "Taking attribute closure {A}+ = {A, B, C, D}. Since closure of {A} contains all attributes of R, {A} is the minimal candidate key."
  },
  {
    id: "q3",
    topic: "Normalization",
    question: "A relation R is in Boyce-Codd Normal Form (BCNF) if for every non-trivial functional dependency X -> Y:",
    options: [
      "A) Y is a prime attribute",
      "B) X is a superkey",
      "C) X is contained in Y",
      "D) Y is a candidate key"
    ],
    correctAnswer: 1,
    explanation: "BCNF is a stricter version of 3NF. It requires that for every non-trivial FD X -> Y, the left hand side X MUST be a superkey of the relation."
  },
  {
    id: "q4",
    topic: "SQL & Relational Algebra",
    question: "Consider the query: SELECT dept_id, COUNT(*) FROM Employee GROUP BY dept_id HAVING COUNT(*) > 5. What does the HAVING clause filter?",
    options: [
      "A) Individual rows before grouping",
      "B) Grouped results after aggregation",
      "C) Columns in the projection list",
      "D) Primary key constraints"
    ],
    correctAnswer: 1,
    explanation: "HAVING operates on aggregated group rows generated by GROUP BY, unlike WHERE which filters individual rows prior to grouping."
  },
  {
    id: "q5",
    topic: "Indexing & File Storage",
    question: "In a B+ Tree index of order m, if a non-root internal node contains k keys, how many pointers/children does it have?",
    options: [
      "A) k - 1",
      "B) k",
      "C) k + 1",
      "D) 2k"
    ],
    correctAnswer: 2,
    explanation: "An internal B/B+ tree node with k keys always points to k + 1 child subtrees."
  },
  {
    id: "q6",
    topic: "Transactions & ACID",
    question: "Which ACID property ensures that once a transaction completes COMMIT, its updates persist in the database even in the event of a system crash?",
    options: [
      "A) Atomicity",
      "B) Consistency",
      "C) Isolation",
      "D) Durability"
    ],
    correctAnswer: 3,
    explanation: "Durability guarantees that committed transaction changes are written to non-volatile storage (WAL/redo log) and survive system crashes."
  },
  {
    id: "q7",
    topic: "Concurrency Control",
    question: "A transaction T1 reads data modified by transaction T2 before T2 has committed. If T2 later aborts, T1 has performed a:",
    options: [
      "A) Dirty Read Anomaly",
      "B) Lost Update Anomaly",
      "C) Phantom Read Anomaly",
      "D) Non-repeatable Read Anomaly"
    ],
    correctAnswer: 0,
    explanation: "Reading uncommitted updates of another transaction that subsequently rolls back causes a Dirty Read anomaly."
  },
  {
    id: "q8",
    topic: "SQL Joins",
    question: "Which type of JOIN returns all records from the left table and matched records from the right table, filling with NULL for unmatched right rows?",
    options: [
      "A) INNER JOIN",
      "B) LEFT OUTER JOIN",
      "C) RIGHT OUTER JOIN",
      "D) FULL OUTER JOIN"
    ],
    correctAnswer: 1,
    explanation: "LEFT OUTER JOIN includes all tuples from the left relation regardless of whether a matching tuple exists in the right relation."
  }
];
